### ISSUE TITLE
ThorLiteScanner Stats Table 

### ISSUE THREAD

**Issue by Benjamin-Hock** [NextronSystems/thor-lite#45] opened 2024-11-07 12:55 UTC
If I execute ThorLite, I always get the same Error message.

It says, that the stat-table cant’t be created because it already exists.

What can I do to fix this error?

![Bildschirmfoto vom 2024-11-07 13-14-32](https://github.com/user-attachments/assets/c5745fba-96d5-435d-a214-e73cdd1f9c09)

**Comment by secDre4mer** [comment] 2024-11-07 15:05
Hi, one possible explanation is that the database file already exists, but THOR Lite doesn't have write permissions. Could you check if this is the case?
The next version will contain a fix for this case (to make the root cause clearer).

**Comment by Benjamin-Hock** [comment] 2024-11-13 12:38
Yeah, if I execute as root, the error is gone.
Thanks.
Now I have to manually change the permissions to view the Output-Files though, because they belong to root

**Comment by secDre4mer** [comment] 2024-11-13 16:35
True. Alternatively, you could adjust the permissions for the DB file (make it world read/writable, or group-read/writable with a group where your user is a member); that should also work.

**Closed as completed by secDre4mer** 2024-11-13 16:35 UTC
